#Load dockerhub image with python version 3.11
FROM python:3.11
#Work dir
WORKDIR /backend
#Install / update neccessary libs / moduls
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY requirements.txt /backend
RUN pip3 install --upgrade pip -r requirements.txt --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org
COPY . /backend
#Port of streamlit web UI
EXPOSE 8300
ENTRYPOINT ["streamlit"]