model_name: credit_risk_test_2
framework: sklearn

ensemble:
  type: voting          # possible right now: voting | stacking | bagging
  voting: soft          # for VotingClassifier
  final_estimator: null # for StackingClassifier, example LogisticRegression
  estimators:
    - name: rf
      type: RandomForestClassifier
      params:
        n_estimators: 200
        max_depth: 5
    - name: lr
      type: LogisticRegression
      params:
        C: 1.0
        solver: liblinear
    - name: xgb
      type: XGBClassifier
      params:
        n_estimators: 300
        learning_rate: 0.05
        max_depth: 4
